export type ActivityType = "conversation" | "fact" | "trueFalse" | "quiz" | "game" | "riddle";

export interface Activity {
  id: string;
  type: ActivityType;
  title: string;
  emoji: string;
  content: string;
  answer?: string;
  options?: string[];
  hint?: string;
  points: number;
  banff?: boolean; // Banff-specific content
}

export const activities: Activity[] = [
  // ── CONVERSATION STARTERS ──────────────────────────────────────────────────
  {
    id: "conv-1",
    type: "conversation",
    title: "Dream Superpower",
    emoji: "🦸",
    content: "If you could have ONE superpower just for this road trip, what would it be and why? (Teleportation and infinite snacks are both valid.)",
    points: 10,
  },
  {
    id: "conv-2",
    type: "conversation",
    title: "Road Trip Food Court",
    emoji: "🍕",
    content: "You get to design the ultimate road trip snack pack. Name your top 3 snacks — one salty, one sweet, one wild card. Go!",
    points: 10,
  },
  {
    id: "conv-3",
    type: "conversation",
    title: "Animal Upgrade",
    emoji: "🐻",
    content: "If you had to live as a Canadian Rockies animal for one week, which would you pick: grizzly bear, mountain goat, bald eagle, or a very fat marmot?",
    points: 10,
  },
  {
    id: "conv-4",
    type: "conversation",
    title: "Banff Time Machine",
    emoji: "⏰",
    content: "If you could visit Banff in ANY time period — 10,000 years ago, 1885 when it was founded, or 100 years in the future — which and why?",
    points: 10,
  },
  {
    id: "conv-5",
    type: "conversation",
    title: "Hot Take",
    emoji: "🌶️",
    content: "Everyone give your most controversial road trip opinion. Examples: 'Rest stops should have waterparks.' 'Audiobooks are better than music.' Go!",
    points: 10,
  },
  {
    id: "conv-6",
    type: "conversation",
    title: "Name That Mountain",
    emoji: "⛰️",
    content: "You just discovered an unnamed mountain. What do you name it and why? (It must be a proper mountain name — no 'Mount Snackface.'… actually, yes snackface.)",
    points: 10,
  },
  {
    id: "conv-7",
    type: "conversation",
    title: "Survival Mode",
    emoji: "🏕️",
    content: "You're stranded in Banff National Park with no phone. What 3 items do you wish you had with you right now?",
    points: 10,
  },
  {
    id: "conv-8",
    type: "conversation",
    title: "Best Memory",
    emoji: "💛",
    content: "What's your favourite family trip memory from the last few years? The weirder the better.",
    points: 10,
  },
  {
    id: "conv-9",
    type: "conversation",
    title: "Road Trip DJ",
    emoji: "🎵",
    content: "You're the car DJ for the next hour. What song do you play first AND what song is absolutely banned?",
    points: 10,
  },
  {
    id: "conv-10",
    type: "conversation",
    title: "Banff Business",
    emoji: "🏪",
    content: "You open a shop in Banff. What do you sell, what's the store name, and what's your weirdest product?",
    points: 10,
  },

  // ── FACTS ─────────────────────────────────────────────────────────────────
  {
    id: "fact-1",
    type: "fact",
    title: "Banff Basics",
    emoji: "🏔️",
    content: "Banff National Park is Canada's OLDEST national park, established in 1885. It covers 6,641 square kilometres — bigger than the entire country of Luxembourg!",
    points: 5,
  },
  {
    id: "fact-2",
    type: "fact",
    title: "Lake Louise Colour",
    emoji: "💎",
    content: "Lake Louise's famous turquoise colour comes from 'rock flour' — ultra-fine powder ground off rocks by glacier movement. When glacial meltwater flows in, it carries tiny particles that scatter sunlight, making the water look impossibly blue-green.",
    points: 5,
  },
  {
    id: "fact-3",
    type: "fact",
    title: "Grizzly Facts",
    emoji: "🐻",
    content: "Grizzly bears can run up to 56 km/h — faster than Usain Bolt. They can also smell food from 29 km away. Your granola bar is NOT safe.",
    points: 5,
  },
  {
    id: "fact-4",
    type: "fact",
    title: "Hot Springs Science",
    emoji: "♨️",
    content: "The Banff Upper Hot Springs stay between 37-40°C year-round. The water originates as rain and snow, seeps 3 km underground where it's heated by geothermal energy, then rises back up — a journey that takes hundreds of years!",
    points: 5,
  },
  {
    id: "fact-5",
    type: "fact",
    title: "Elk in Town",
    emoji: "🦌",
    content: "Banff town has a larger elk population than some Canadian cities have deer. They regularly walk down main street, graze in hotel lawns, and occasionally hold up traffic. They have the right of way.",
    points: 5,
  },
  {
    id: "fact-6",
    type: "fact",
    title: "The Icefields Parkway",
    emoji: "🛣️",
    content: "The Icefields Parkway (Highway 93) is widely considered one of the most scenic drives on Earth. It passes 100+ glaciers and icefields, 6 national parks, and took only 228 days to build in the 1930s during the Great Depression.",
    points: 5,
  },
  {
    id: "fact-7",
    type: "fact",
    title: "Wildlife Crossing",
    emoji: "🐾",
    content: "Banff has 38 wildlife crossing structures along the Trans-Canada Highway — the most of any national park in the world. Cameras show wolves, bears, cougars, deer, and even moose using them. Over 200,000 animal crossings have been recorded!",
    points: 5,
  },
  {
    id: "fact-8",
    type: "fact",
    title: "Mountain Goat Hooves",
    emoji: "🐐",
    content: "Mountain goat hooves have a hard outer edge for grip and a soft rubbery pad inside for traction — like built-in climbing shoes. They can scale nearly vertical rock faces and leap 3.5 metres in a single bound.",
    points: 5,
  },
  {
    id: "fact-9",
    type: "fact",
    title: "Banff Town Pop",
    emoji: "🏘️",
    content: "Only about 8,000 people live in Banff year-round — but the park sees over 4 MILLION visitors annually. That's 500 tourists for every resident!",
    points: 5,
  },
  {
    id: "fact-10",
    type: "fact",
    title: "The Rocky Mountains Age",
    emoji: "🪨",
    content: "The Canadian Rockies are about 170 million years old. The rocks you see contain fossils from when this area was a shallow tropical sea. Some of the fossils here are 500 million years old!",
    points: 5,
  },

  // ── TRUE / FALSE ───────────────────────────────────────────────────────────
  {
    id: "tf-1",
    type: "trueFalse",
    title: "Bear Fact Check",
    emoji: "🐻",
    content: "Playing dead works against a grizzly bear attack.",
    answer: "true",
    hint: "It works for defensive attacks — a bear protecting cubs or food. For a predatory attack, fight back!",
    points: 15,
  },
  {
    id: "tf-2",
    type: "trueFalse",
    title: "Moose vs Horse",
    emoji: "🦌",
    content: "A moose can weigh more than a horse.",
    answer: "true",
    hint: "Large bull moose can weigh up to 700 kg. The average horse is 450-500 kg.",
    points: 15,
  },
  {
    id: "tf-3",
    type: "trueFalse",
    title: "Lake Louise Swim",
    emoji: "🏊",
    content: "Lake Louise is warm enough to swim in during summer.",
    answer: "false",
    hint: "Lake Louise is glacier-fed. Even in July it's around 4°C — cold enough to cause hypothermia in minutes!",
    points: 15,
  },
  {
    id: "tf-4",
    type: "trueFalse",
    title: "Banff Birthday",
    emoji: "🎂",
    content: "Banff National Park is older than the province of Alberta.",
    answer: "true",
    hint: "Banff was established in 1885. Alberta only became a province in 1905 — 20 years later!",
    points: 15,
  },
  {
    id: "tf-5",
    type: "trueFalse",
    title: "Howling Myth",
    emoji: "🐺",
    content: "Wolves howl at the moon.",
    answer: "false",
    hint: "Wolves howl to communicate with the pack — to find lost members, warn rivals, and coordinate hunts. The moon has nothing to do with it. They just tend to howl at night when the moon is visible!",
    points: 15,
  },
  {
    id: "tf-6",
    type: "trueFalse",
    title: "Glacier Speed",
    emoji: "🧊",
    content: "Glaciers can move faster than a person walks.",
    answer: "false",
    hint: "Most glaciers move 1–2 metres per DAY at most. The fastest glaciers on Earth move about 20–30 metres per day. Walking speed is about 5 km per hour.",
    points: 15,
  },
  {
    id: "tf-7",
    type: "trueFalse",
    title: "Canadian Rockies",
    emoji: "🇨🇦",
    content: "The Canadian Rockies extend into 3 provinces.",
    answer: "false",
    hint: "They span 2 provinces: Alberta and British Columbia. They do NOT extend into Saskatchewan.",
    points: 15,
  },
  {
    id: "tf-8",
    type: "trueFalse",
    title: "Bear Spray",
    emoji: "🧴",
    content: "Bear spray is more effective than a gun at stopping a bear attack.",
    answer: "true",
    hint: "Studies by bear biologist Stephen Herrero show bear spray stops attacks 92% of the time vs guns stopping attacks 67% of the time. Spray every time!",
    points: 15,
  },
  {
    id: "tf-9",
    type: "trueFalse",
    title: "Banff Springs Hotel",
    emoji: "🏰",
    content: "The Banff Springs Hotel was designed to look like a Scottish baronial castle.",
    answer: "true",
    hint: "It was deliberately built to resemble a Scottish baronial castle to appeal to European tourists arriving by CPR train. It opened in 1888.",
    points: 15,
  },
  {
    id: "tf-10",
    type: "trueFalse",
    title: "Pika Survival",
    emoji: "🐹",
    content: "Pikas (those tiny round mountain animals) hibernate during winter.",
    answer: "false",
    hint: "Pikas don't hibernate! They spend all summer gathering grasses to make haypiles under rocks. They stay active all winter under the snow, living off their stored food.",
    points: 15,
  },

  // ── QUIZZES ────────────────────────────────────────────────────────────────
  {
    id: "quiz-1",
    type: "quiz",
    title: "How High?",
    emoji: "📏",
    content: "Approximately how tall is Mount Rundle, one of Banff's most iconic peaks?",
    options: ["1,200 m", "2,949 m", "4,100 m", "5,500 m"],
    answer: "2,949 m",
    hint: "It's the dramatic slanted mountain visible right from Banff townsite.",
    points: 20,
  },
  {
    id: "quiz-2",
    type: "quiz",
    title: "Wildlife ID",
    emoji: "🦙",
    content: "Which animal has a hump on its shoulders, is native to the Canadian Rockies, and is NOT a camel?",
    options: ["Bison", "Grizzly Bear", "Moose", "Bighorn Sheep"],
    answer: "Grizzly Bear",
    hint: "Grizzlies have a distinctive muscular hump — it's actually a shoulder muscle mass for digging.",
    points: 20,
  },
  {
    id: "quiz-3",
    type: "quiz",
    title: "Park Pass",
    emoji: "🎟️",
    content: "Which document do you need to enter Banff National Park?",
    options: ["Driver's License", "Parks Canada Discovery Pass", "Canadian Passport", "Library Card"],
    answer: "Parks Canada Discovery Pass",
    hint: "You need a Parks Canada pass or can pay a daily fee at the gate.",
    points: 20,
  },
  {
    id: "quiz-4",
    type: "quiz",
    title: "Speed Trap",
    emoji: "🚗",
    content: "What is the standard speed limit inside most of Banff National Park?",
    options: ["90 km/h", "80 km/h", "60 km/h", "110 km/h"],
    answer: "90 km/h",
    hint: "Lower speed limits reduce wildlife-vehicle collisions.",
    points: 20,
  },
  {
    id: "quiz-5",
    type: "quiz",
    title: "Lake Colour",
    emoji: "🎨",
    content: "What gives glacier lakes their brilliant turquoise and green colour?",
    options: ["Algae blooms", "Rock flour from glaciers", "Copper deposits", "Blue food colouring (tourist trap)"],
    answer: "Rock flour from glaciers",
    hint: "Fine glacial particles scatter blue-green light wavelengths.",
    points: 20,
  },
  {
    id: "quiz-6",
    type: "quiz",
    title: "Banff Year",
    emoji: "📅",
    content: "In what year was Banff National Park officially established?",
    options: ["1871", "1885", "1902", "1920"],
    answer: "1885",
    hint: "It was Canada's first national park, created by PM John A. Macdonald.",
    points: 20,
  },
  {
    id: "quiz-7",
    type: "quiz",
    title: "Rocky Mountain High",
    emoji: "🏔️",
    content: "What is the highest peak in the Canadian Rockies?",
    options: ["Mount Rundle", "Mount Temple", "Mount Robson", "Cascade Mountain"],
    answer: "Mount Robson",
    hint: "It's nicknamed 'King of the Canadian Rockies' and is 3,954 m tall.",
    points: 20,
  },
  {
    id: "quiz-8",
    type: "quiz",
    title: "Bear Types",
    emoji: "🐻",
    content: "Which bears live in Banff National Park?",
    options: [
      "Only black bears",
      "Only grizzly bears",
      "Both black bears and grizzly bears",
      "Polar bears",
    ],
    answer: "Both black bears and grizzly bears",
    hint: "Both species share the park but have different habitats and behaviours.",
    points: 20,
  },
  {
    id: "quiz-9",
    type: "quiz",
    title: "Bow River",
    emoji: "🌊",
    content: "The Bow River that flows through Banff eventually flows into which major river?",
    options: ["Saskatchewan River", "Columbia River", "Fraser River", "Athabasca River"],
    answer: "Saskatchewan River",
    hint: "The Bow joins the Oldman River to form the South Saskatchewan River.",
    points: 20,
  },
  {
    id: "quiz-10",
    type: "quiz",
    title: "Marmot Alarm",
    emoji: "🐾",
    content: "What do hoary marmots (big fluffy mountain rodents) do when they sense danger?",
    options: ["Play dead", "Emit a loud whistle", "Change colour", "Sprint at the predator"],
    answer: "Emit a loud whistle",
    hint: "They're sometimes called 'whistlers' because of this alarm call!",
    points: 20,
  },

  // ── GAMES ─────────────────────────────────────────────────────────────────
  {
    id: "game-1",
    type: "game",
    title: "Alphabet Mountains",
    emoji: "🔤",
    content: "Go around the car naming Banff/mountain things in alphabetical order. A = Avalanche, B = Bear, C = Canyon... Keep going without repeating! If you get stuck past Q you all win a snack.",
    points: 25,
  },
  {
    id: "game-2",
    type: "game",
    title: "20 Questions: Wildlife",
    emoji: "🐾",
    content: "Someone picks a Canadian Rockies animal (secretly). Everyone else asks YES/NO questions to figure it out. Max 20 questions! The guesser with the fewest questions wins bragging rights.",
    points: 25,
  },
  {
    id: "game-3",
    type: "game",
    title: "Spot That Animal",
    emoji: "👀",
    content: "ACTIVE WINDOW GAME: First person to spot a real animal outside the car (not on a sign) wins 50 bonus points. Bird = 5 pts. Deer/elk = 10 pts. Bear = 50 pts. Mythical creature = 100 pts.",
    points: 25,
  },
  {
    id: "game-4",
    type: "game",
    title: "Road Trip Bingo",
    emoji: "🎯",
    content: "Everyone picks 5 things to spot on the road. Mix it up: a red barn, a motorcycle, a dog in a car, a camper van, a Canadian flag. First to spot all 5 wins! Call out when you see one.",
    points: 25,
  },
  {
    id: "game-5",
    type: "game",
    title: "Would You Rather: Wilderness",
    emoji: "🤔",
    content: "Battle it out! Would you rather: (A) Be chased by a bear for 30 seconds OR (B) Sleep in a tent knowing there's a skunk nearby? Vote and debate! No fence-sitting allowed.",
    points: 25,
  },
  {
    id: "game-6",
    type: "game",
    title: "Mountain Name Generator",
    emoji: "🏔️",
    content: "Create your OFFICIAL mountain name: [Your middle name OR pet's name] + [Last thing you ate] + [Current mood] Mountain. Mine is... go! Share the best ones.",
    points: 25,
  },
  {
    id: "game-7",
    type: "game",
    title: "Story Mountain",
    emoji: "📖",
    content: "Build a story together! One sentence each, going around the car. Start: 'A grizzly bear walked into the Banff Starbucks and ordered a...' Every sentence must end on a cliffhanger.",
    points: 25,
  },
  {
    id: "game-8",
    type: "game",
    title: "License Plate Bingo",
    emoji: "🚘",
    content: "Spot license plates from different provinces/states! Alberta = 1 pt. Other Canadian province = 2 pts. US state = 3 pts. Whoever spots the most unique plates wins by the end of the day.",
    points: 25,
  },
  {
    id: "game-9",
    type: "game",
    title: "The Quiet Game... Kind Of",
    emoji: "🤫",
    content: "Everyone stay quiet for 60 seconds while looking out the window. After the minute, describe the most interesting thing you noticed in silence. No phones! The most creative observation wins.",
    points: 25,
  },
  {
    id: "game-10",
    type: "game",
    title: "Campfire Karaoke",
    emoji: "🎤",
    content: "Pick a song about travel, nature, or adventure. Everyone takes turns singing ONE line, then the next person continues — even if they don't know the words. Most creative improvisation wins.",
    points: 25,
  },

  // ── RIDDLES ───────────────────────────────────────────────────────────────
  {
    id: "rid-1",
    type: "riddle",
    title: "Mountain Riddle",
    emoji: "🤓",
    content: "I have a white hat in winter, a green coat in summer, I'm taller than any building, and I never move. What am I?",
    answer: "A mountain!",
    hint: "Think about what's on top during different seasons...",
    points: 30,
  },
  {
    id: "rid-2",
    type: "riddle",
    title: "River Riddle",
    emoji: "🌊",
    content: "I run downhill without legs, I roar without a mouth, I carry rocks without hands. The fish love me and the mountains made me. What am I?",
    answer: "A river!",
    hint: "You'll see a lot of me along the Icefields Parkway...",
    points: 30,
  },
  {
    id: "rid-3",
    type: "riddle",
    title: "Bear Riddle",
    emoji: "🐻",
    content: "I sleep through the cold, I eat all summer long, I have a hump on my back but I'm no camel, and park wardens put up signs warning you about me. What am I?",
    answer: "A grizzly bear!",
    hint: "You'll want to make noise while hiking in Banff to avoid surprising one...",
    points: 30,
  },
  {
    id: "rid-4",
    type: "riddle",
    title: "Ice Riddle",
    emoji: "🧊",
    content: "I'm made of snow but I'm not a snowman. I move but I'm not alive. I'm thousands of years old but I'm slowly shrinking. I colour lakes with my dust. What am I?",
    answer: "A glacier!",
    hint: "The Athabasca one is famous...",
    points: 30,
  },
  {
    id: "rid-5",
    type: "riddle",
    title: "Road Riddle",
    emoji: "🛣️",
    content: "I go from Banff to Jasper, I'm called a Parkway, I pass a hundred glaciers but I'm never cold, and I'm considered one of the world's most beautiful roads. What am I?",
    answer: "The Icefields Parkway!",
    hint: "Highway 93...",
    points: 30,
  },
  {
    id: "rid-6",
    type: "riddle",
    title: "Forest Riddle",
    emoji: "🌲",
    content: "I have thousands of needles but I've never sewed a thing. I stand in the mountain cold and smell amazing. Moose eat my bark and squirrels love my seeds. What am I?",
    answer: "A pine (or spruce) tree!",
    hint: "Look out the window — you're probably surrounded by me right now...",
    points: 30,
  },
  {
    id: "rid-7",
    type: "riddle",
    title: "Hotel Riddle",
    emoji: "🏰",
    content: "I look like a Scottish castle, I'm one of Canada's most famous buildings, I sit where the Bow and Spray rivers meet, and I've hosted royalty. What am I?",
    answer: "The Banff Springs Hotel!",
    hint: "It was built by the Canadian Pacific Railway in 1888...",
    points: 30,
  },
  {
    id: "rid-8",
    type: "riddle",
    title: "Little Guy Riddle",
    emoji: "🐹",
    content: "I'm tiny and round like a potato with ears. I don't hibernate but I live under rocks. I spend all summer making a secret food pile. A single whistle blast means danger. What am I?",
    answer: "A pika!",
    hint: "They live in rocky alpine slopes and are related to rabbits...",
    points: 30,
  },
  {
    id: "rid-9",
    type: "riddle",
    title: "Water Riddle",
    emoji: "♨️",
    content: "I start as rain on a mountain, sink 3 kilometres underground, get heated for 500 years, then bubble up warm in a rocky pool. People have soaked in me for thousands of years. What am I?",
    answer: "Hot springs!",
    hint: "There are famous ones on Sulphur Mountain in Banff...",
    points: 30,
  },
  {
    id: "rid-10",
    type: "riddle",
    title: "Night Sky Riddle",
    emoji: "🌌",
    content: "I'm brightest where there are no cities, I contain 200 billion suns, and on a clear night in Banff you can see my cloudy arm stretch across the sky. What am I?",
    answer: "The Milky Way galaxy!",
    hint: "Banff is a Dark Sky Preserve — perfect for seeing me...",
    points: 30,
  },

  // ── BONUS BANFF ACTIVITIES ────────────────────────────────────────────────
  {
    id: "bonus-1",
    type: "fact",
    title: "Banff Dark Sky",
    emoji: "🌠",
    content: "Banff National Park is a designated Dark Sky Preserve. On a clear night you can see the Milky Way, thousands of stars, and sometimes the Northern Lights. In June, look north after midnight!",
    points: 5,
  },
  {
    id: "bonus-2",
    type: "conversation",
    title: "Trip Traditions",
    emoji: "⭐",
    content: "What should be our official family road trip tradition? Something we do every time — a snack, a stop, a song, a game. Vote and commit!",
    points: 10,
  },
  {
    id: "bonus-3",
    type: "quiz",
    title: "Banff Elevation",
    emoji: "📐",
    content: "What is the elevation of Banff townsite above sea level?",
    options: ["750 m", "1,383 m", "2,000 m", "2,800 m"],
    answer: "1,383 m",
    hint: "That's why some people feel slightly short of breath at first!",
    points: 20,
  },
  {
    id: "bonus-4",
    type: "trueFalse",
    title: "Banff Water",
    emoji: "💧",
    content: "Banff's tap water comes directly from glacial meltwater and is among the cleanest drinking water in the world.",
    answer: "true",
    hint: "Banff gets its water from the Bow River, which is fed by glacier runoff. It's processed and tested — genuinely excellent quality.",
    points: 15,
  },
  {
    id: "bonus-5",
    type: "game",
    title: "Photo Challenge",
    emoji: "📸",
    content: "Everyone takes one photo before the next stop. Theme: 'Most Creative Mountain Shot.' At the next stop, everyone shows their photo. Family vote decides the winner — they pick the next snack stop!",
    points: 25,
  },
  {
    id: "bonus-6",
    type: "conversation",
    title: "Return Trip Dream",
    emoji: "✈️",
    content: "If you could return to Banff with unlimited money and time, what would you do differently? What would you add to this trip right now if you could?",
    points: 10,
  },
  {
    id: "bonus-7",
    type: "riddle",
    title: "The Banff Riddle",
    emoji: "🏔️",
    content: "I'm in a province but also a town. I'm in a park but also a hotel. I'm Canadian but my name comes from a Scottish town. I sit between two rivers in the shadow of Sulphur Mountain. What am I?",
    answer: "Banff!",
    hint: "Named after Banff, Aberdeenshire, Scotland, by CPR president George Stephen...",
    points: 30,
  },
];

// ── HELPERS ────────────────────────────────────────────────────────────────

export function getRandomActivity(excludeIds: string[] = []): Activity {
  const available = activities.filter((a) => !excludeIds.includes(a.id));
  if (available.length === 0) return activities[Math.floor(Math.random() * activities.length)];
  return available[Math.floor(Math.random() * available.length)];
}

export function getActivityById(id: string): Activity | undefined {
  return activities.find((a) => a.id === id);
}

export const TYPE_LABELS: Record<ActivityType, string> = {
  conversation: "Talk It Out",
  fact: "Fun Fact",
  trueFalse: "True or False",
  quiz: "Quiz Time",
  game: "Mini Game",
  riddle: "Riddle Me This",
};

export const TYPE_COLORS: Record<ActivityType, string> = {
  conversation: "from-purple-500 to-indigo-600",
  fact: "from-blue-500 to-cyan-600",
  trueFalse: "from-orange-500 to-amber-600",
  quiz: "from-green-500 to-emerald-600",
  game: "from-pink-500 to-rose-600",
  riddle: "from-yellow-500 to-orange-600",
};

export const TYPE_BG: Record<ActivityType, string> = {
  conversation: "bg-purple-50 border-purple-200",
  fact: "bg-blue-50 border-blue-200",
  trueFalse: "bg-orange-50 border-orange-200",
  quiz: "bg-green-50 border-green-200",
  game: "bg-pink-50 border-pink-200",
  riddle: "bg-yellow-50 border-yellow-200",
};
