export type ActivityType = "conversation" | "fact" | "trueFalse" | "quiz" | "game" | "riddle" | "rhyme";

export interface Activity {
  id: string;
  type: ActivityType;
  title: string;
  emoji: string;
  content: string;
  answer?: string;
  options?: string[];
  hint?: string;
  points: number;
  banff?: boolean; // Banff-specific content
}

export const activities: Activity[] = [
  // ── CONVERSATION STARTERS ──────────────────────────────────────────────────
  {
    id: "conv-1",
    type: "conversation",
    title: "Dream Superpower",
    emoji: "🦸",
    content: "If you could have ONE superpower just for this road trip, what would it be and why? (Teleportation and infinite snacks are both valid.)",
    points: 10,
  },
  {
    id: "conv-2",
    type: "conversation",
    title: "Road Trip Food Court",
    emoji: "🍕",
    content: "You get to design the ultimate road trip snack pack. Name your top 3 snacks — one salty, one sweet, one wild card. Go!",
    points: 10,
  },
  {
    id: "conv-3",
    type: "conversation",
    title: "Animal Upgrade",
    emoji: "🐻",
    content: "If you had to live as a Canadian Rockies animal for one week, which would you pick: grizzly bear, mountain goat, bald eagle, or a very fat marmot?",
    points: 10,
  },
  {
    id: "conv-4",
    type: "conversation",
    title: "Banff Time Machine",
    emoji: "⏰",
    content: "If you could visit Banff in ANY time period — 10,000 years ago, 1885 when it was founded, or 100 years in the future — which and why?",
    points: 10,
  },
  {
    id: "conv-5",
    type: "conversation",
    title: "Hot Take",
    emoji: "🌶️",
    content: "Everyone give your most controversial road trip opinion. Examples: 'Rest stops should have waterparks.' 'Audiobooks are better than music.' Go!",
    points: 10,
  },
  {
    id: "conv-6",
    type: "conversation",
    title: "Name That Mountain",
    emoji: "⛰️",
    content: "You just discovered an unnamed mountain. What do you name it and why? (It must be a proper mountain name — no 'Mount Snackface.'… actually, yes snackface.)",
    points: 10,
  },
  {
    id: "conv-7",
    type: "conversation",
    title: "Survival Mode",
    emoji: "🏕️",
    content: "You're stranded in Banff National Park with no phone. What 3 items do you wish you had with you right now?",
    points: 10,
  },
  {
    id: "conv-8",
    type: "conversation",
    title: "Best Memory",
    emoji: "💛",
    content: "What's your favourite family trip memory from the last few years? The weirder the better.",
    points: 10,
  },
  {
    id: "conv-9",
    type: "conversation",
    title: "Road Trip DJ",
    emoji: "🎵",
    content: "You're the car DJ for the next hour. What song do you play first AND what song is absolutely banned?",
    points: 10,
  },
  {
    id: "conv-10",
    type: "conversation",
    title: "Banff Business",
    emoji: "🏪",
    content: "You open a shop in Banff. What do you sell, what's the store name, and what's your weirdest product?",
    points: 10,
  },

  // ── FACTS ─────────────────────────────────────────────────────────────────
  {
    id: "fact-1",
    type: "fact",
    title: "Banff Basics",
    emoji: "🏔️",
    content: "Banff National Park is Canada's OLDEST national park, established in 1885. It covers 6,641 square kilometres — bigger than the entire country of Luxembourg!",
    points: 5,
  },
  {
    id: "fact-2",
    type: "fact",
    title: "Lake Louise Colour",
    emoji: "💎",
    content: "Lake Louise's famous turquoise colour comes from 'rock flour' — ultra-fine powder ground off rocks by glacier movement. When glacial meltwater flows in, it carries tiny particles that scatter sunlight, making the water look impossibly blue-green.",
    points: 5,
  },
  {
    id: "fact-3",
    type: "fact",
    title: "Grizzly Facts",
    emoji: "🐻",
    content: "Grizzly bears can run up to 56 km/h — faster than Usain Bolt. They can also smell food from 29 km away. Your granola bar is NOT safe.",
    points: 5,
  },
  {
    id: "fact-4",
    type: "fact",
    title: "Hot Springs Science",
    emoji: "♨️",
    content: "The Banff Upper Hot Springs stay between 37-40°C year-round. The water originates as rain and snow, seeps 3 km underground where it's heated by geothermal energy, then rises back up — a journey that takes hundreds of years!",
    points: 5,
  },
  {
    id: "fact-5",
    type: "fact",
    title: "Elk in Town",
    emoji: "🦌",
    content: "Banff town has a larger elk population than some Canadian cities have deer. They regularly walk down main street, graze in hotel lawns, and occasionally hold up traffic. They have the right of way.",
    points: 5,
  },
  {
    id: "fact-6",
    type: "fact",
    title: "The Icefields Parkway",
    emoji: "🛣️",
    content: "The Icefields Parkway (Highway 93) is widely considered one of the most scenic drives on Earth. It passes 100+ glaciers and icefields, 6 national parks, and took only 228 days to build in the 1930s during the Great Depression.",
    points: 5,
  },
  {
    id: "fact-7",
    type: "fact",
    title: "Wildlife Crossing",
    emoji: "🐾",
    content: "Banff has 38 wildlife crossing structures along the Trans-Canada Highway — the most of any national park in the world. Cameras show wolves, bears, cougars, deer, and even moose using them. Over 200,000 animal crossings have been recorded!",
    points: 5,
  },
  {
    id: "fact-8",
    type: "fact",
    title: "Mountain Goat Hooves",
    emoji: "🐐",
    content: "Mountain goat hooves have a hard outer edge for grip and a soft rubbery pad inside for traction — like built-in climbing shoes. They can scale nearly vertical rock faces and leap 3.5 metres in a single bound.",
    points: 5,
  },
  {
    id: "fact-9",
    type: "fact",
    title: "Banff Town Pop",
    emoji: "🏘️",
    content: "Only about 8,000 people live in Banff year-round — but the park sees over 4 MILLION visitors annually. That's 500 tourists for every resident!",
    points: 5,
  },
  {
    id: "fact-10",
    type: "fact",
    title: "The Rocky Mountains Age",
    emoji: "🪨",
    content: "The Canadian Rockies are about 170 million years old. The rocks you see contain fossils from when this area was a shallow tropical sea. Some of the fossils here are 500 million years old!",
    points: 5,
  },

  // ── TRUE / FALSE ───────────────────────────────────────────────────────────
  {
    id: "tf-1",
    type: "trueFalse",
    title: "Bear Fact Check",
    emoji: "🐻",
    content: "Playing dead works against a grizzly bear attack.",
    answer: "true",
    hint: "It works for defensive attacks — a bear protecting cubs or food. For a predatory attack, fight back!",
    points: 15,
  },
  {
    id: "tf-2",
    type: "trueFalse",
    title: "Moose vs Horse",
    emoji: "🦌",
    content: "A moose can weigh more than a horse.",
    answer: "true",
    hint: "Large bull moose can weigh up to 700 kg. The average horse is 450-500 kg.",
    points: 15,
  },
  {
    id: "tf-3",
    type: "trueFalse",
    title: "Lake Louise Swim",
    emoji: "🏊",
    content: "Lake Louise is warm enough to swim in during summer.",
    answer: "false",
    hint: "Lake Louise is glacier-fed. Even in July it's around 4°C — cold enough to cause hypothermia in minutes!",
    points: 15,
  },
  {
    id: "tf-4",
    type: "trueFalse",
    title: "Banff Birthday",
    emoji: "🎂",
    content: "Banff National Park is older than the province of Alberta.",
    answer: "true",
    hint: "Banff was established in 1885. Alberta only became a province in 1905 — 20 years later!",
    points: 15,
  },
  {
    id: "tf-5",
    type: "trueFalse",
    title: "Howling Myth",
    emoji: "🐺",
    content: "Wolves howl at the moon.",
    answer: "false",
    hint: "Wolves howl to communicate with the pack — to find lost members, warn rivals, and coordinate hunts. The moon has nothing to do with it. They just tend to howl at night when the moon is visible!",
    points: 15,
  },
  {
    id: "tf-6",
    type: "trueFalse",
    title: "Glacier Speed",
    emoji: "🧊",
    content: "Glaciers can move faster than a person walks.",
    answer: "false",
    hint: "Most glaciers move 1–2 metres per DAY at most. The fastest glaciers on Earth move about 20–30 metres per day. Walking speed is about 5 km per hour.",
    points: 15,
  },
  {
    id: "tf-7",
    type: "trueFalse",
    title: "Canadian Rockies",
    emoji: "🇨🇦",
    content: "The Canadian Rockies extend into 3 provinces.",
    answer: "false",
    hint: "They span 2 provinces: Alberta and British Columbia. They do NOT extend into Saskatchewan.",
    points: 15,
  },
  {
    id: "tf-8",
    type: "trueFalse",
    title: "Bear Spray",
    emoji: "🧴",
    content: "Bear spray is more effective than a gun at stopping a bear attack.",
    answer: "true",
    hint: "Studies by bear biologist Stephen Herrero show bear spray stops attacks 92% of the time vs guns stopping attacks 67% of the time. Spray every time!",
    points: 15,
  },
  {
    id: "tf-9",
    type: "trueFalse",
    title: "Banff Springs Hotel",
    emoji: "🏰",
    content: "The Banff Springs Hotel was designed to look like a Scottish baronial castle.",
    answer: "true",
    hint: "It was deliberately built to resemble a Scottish baronial castle to appeal to European tourists arriving by CPR train. It opened in 1888.",
    points: 15,
  },
  {
    id: "tf-10",
    type: "trueFalse",
    title: "Pika Survival",
    emoji: "🐹",
    content: "Pikas (those tiny round mountain animals) hibernate during winter.",
    answer: "false",
    hint: "Pikas don't hibernate! They spend all summer gathering grasses to make haypiles under rocks. They stay active all winter under the snow, living off their stored food.",
    points: 15,
  },

  // ── QUIZZES ────────────────────────────────────────────────────────────────
  {
    id: "quiz-1",
    type: "quiz",
    title: "How High?",
    emoji: "📏",
    content: "Approximately how tall is Mount Rundle, one of Banff's most iconic peaks?",
    options: ["1,200 m", "2,949 m", "4,100 m", "5,500 m"],
    answer: "2,949 m",
    hint: "It's the dramatic slanted mountain visible right from Banff townsite.",
    points: 20,
  },
  {
    id: "quiz-2",
    type: "quiz",
    title: "Wildlife ID",
    emoji: "🦙",
    content: "Which animal has a hump on its shoulders, is native to the Canadian Rockies, and is NOT a camel?",
    options: ["Bison", "Grizzly Bear", "Moose", "Bighorn Sheep"],
    answer: "Grizzly Bear",
    hint: "Grizzlies have a distinctive muscular hump — it's actually a shoulder muscle mass for digging.",
    points: 20,
  },
  {
    id: "quiz-3",
    type: "quiz",
    title: "Park Pass",
    emoji: "🎟️",
    content: "Which document do you need to enter Banff National Park?",
    options: ["Driver's License", "Parks Canada Discovery Pass", "Canadian Passport", "Library Card"],
    answer: "Parks Canada Discovery Pass",
    hint: "You need a Parks Canada pass or can pay a daily fee at the gate.",
    points: 20,
  },
  {
    id: "quiz-4",
    type: "quiz",
    title: "Speed Trap",
    emoji: "🚗",
    content: "What is the standard speed limit inside most of Banff National Park?",
    options: ["90 km/h", "80 km/h", "60 km/h", "110 km/h"],
    answer: "90 km/h",
    hint: "Lower speed limits reduce wildlife-vehicle collisions.",
    points: 20,
  },
  {
    id: "quiz-5",
    type: "quiz",
    title: "Lake Colour",
    emoji: "🎨",
    content: "What gives glacier lakes their brilliant turquoise and green colour?",
    options: ["Algae blooms", "Rock flour from glaciers", "Copper deposits", "Blue food colouring (tourist trap)"],
    answer: "Rock flour from glaciers",
    hint: "Fine glacial particles scatter blue-green light wavelengths.",
    points: 20,
  },
  {
    id: "quiz-6",
    type: "quiz",
    title: "Banff Year",
    emoji: "📅",
    content: "In what year was Banff National Park officially established?",
    options: ["1871", "1885", "1902", "1920"],
    answer: "1885",
    hint: "It was Canada's first national park, created by PM John A. Macdonald.",
    points: 20,
  },
  {
    id: "quiz-7",
    type: "quiz",
    title: "Rocky Mountain High",
    emoji: "🏔️",
    content: "What is the highest peak in the Canadian Rockies?",
    options: ["Mount Rundle", "Mount Temple", "Mount Robson", "Cascade Mountain"],
    answer: "Mount Robson",
    hint: "It's nicknamed 'King of the Canadian Rockies' and is 3,954 m tall.",
    points: 20,
  },
  {
    id: "quiz-8",
    type: "quiz",
    title: "Bear Types",
    emoji: "🐻",
    content: "Which bears live in Banff National Park?",
    options: [
      "Only black bears",
      "Only grizzly bears",
      "Both black bears and grizzly bears",
      "Polar bears",
    ],
    answer: "Both black bears and grizzly bears",
    hint: "Both species share the park but have different habitats and behaviours.",
    points: 20,
  },
  {
    id: "quiz-9",
    type: "quiz",
    title: "Bow River",
    emoji: "🌊",
    content: "The Bow River that flows through Banff eventually flows into which major river?",
    options: ["Saskatchewan River", "Columbia River", "Fraser River", "Athabasca River"],
    answer: "Saskatchewan River",
    hint: "The Bow joins the Oldman River to form the South Saskatchewan River.",
    points: 20,
  },
  {
    id: "quiz-10",
    type: "quiz",
    title: "Marmot Alarm",
    emoji: "🐾",
    content: "What do hoary marmots (big fluffy mountain rodents) do when they sense danger?",
    options: ["Play dead", "Emit a loud whistle", "Change colour", "Sprint at the predator"],
    answer: "Emit a loud whistle",
    hint: "They're sometimes called 'whistlers' because of this alarm call!",
    points: 20,
  },

  // ── GAMES ─────────────────────────────────────────────────────────────────
  {
    id: "game-1",
    type: "game",
    title: "Alphabet Mountains",
    emoji: "🔤",
    content: "Go around the car naming Banff/mountain things in alphabetical order. A = Avalanche, B = Bear, C = Canyon... Keep going without repeating! If you get stuck past Q you all win a snack.",
    points: 25,
  },
  {
    id: "game-2",
    type: "game",
    title: "20 Questions: Wildlife",
    emoji: "🐾",
    content: "Someone picks a Canadian Rockies animal (secretly). Everyone else asks YES/NO questions to figure it out. Max 20 questions! The guesser with the fewest questions wins bragging rights.",
    points: 25,
  },
  {
    id: "game-3",
    type: "game",
    title: "Spot That Animal",
    emoji: "👀",
    content: "ACTIVE WINDOW GAME: First person to spot a real animal outside the car (not on a sign) wins 50 bonus points. Bird = 5 pts. Deer/elk = 10 pts. Bear = 50 pts. Mythical creature = 100 pts.",
    points: 25,
  },
  {
    id: "game-4",
    type: "game",
    title: "Road Trip Bingo",
    emoji: "🎯",
    content: "Everyone picks 5 things to spot on the road. Mix it up: a red barn, a motorcycle, a dog in a car, a camper van, a Canadian flag. First to spot all 5 wins! Call out when you see one.",
    points: 25,
  },
  {
    id: "game-5",
    type: "game",
    title: "Would You Rather: Wilderness",
    emoji: "🤔",
    content: "Battle it out! Would you rather: (A) Be chased by a bear for 30 seconds OR (B) Sleep in a tent knowing there's a skunk nearby? Vote and debate! No fence-sitting allowed.",
    points: 25,
  },
  {
    id: "game-6",
    type: "game",
    title: "Mountain Name Generator",
    emoji: "🏔️",
    content: "Create your OFFICIAL mountain name: [Your middle name OR pet's name] + [Last thing you ate] + [Current mood] Mountain. Mine is... go! Share the best ones.",
    points: 25,
  },
  {
    id: "game-7",
    type: "game",
    title: "Story Mountain",
    emoji: "📖",
    content: "Build a story together! One sentence each, going around the car. Start: 'A grizzly bear walked into the Banff Starbucks and ordered a...' Every sentence must end on a cliffhanger.",
    points: 25,
  },
  {
    id: "game-8",
    type: "game",
    title: "License Plate Bingo",
    emoji: "🚘",
    content: "Spot license plates from different provinces/states! Alberta = 1 pt. Other Canadian province = 2 pts. US state = 3 pts. Whoever spots the most unique plates wins by the end of the day.",
    points: 25,
  },
  {
    id: "game-9",
    type: "game",
    title: "The Quiet Game... Kind Of",
    emoji: "🤫",
    content: "Everyone stay quiet for 60 seconds while looking out the window. After the minute, describe the most interesting thing you noticed in silence. No phones! The most creative observation wins.",
    points: 25,
  },
  {
    id: "game-10",
    type: "game",
    title: "Campfire Karaoke",
    emoji: "🎤",
    content: "Pick a song about travel, nature, or adventure. Everyone takes turns singing ONE line, then the next person continues — even if they don't know the words. Most creative improvisation wins.",
    points: 25,
  },

  // ── RIDDLES ───────────────────────────────────────────────────────────────
  {
    id: "rid-1",
    type: "riddle",
    title: "Mountain Riddle",
    emoji: "🤓",
    content: "I have a white hat in winter, a green coat in summer, I'm taller than any building, and I never move. What am I?",
    answer: "A mountain!",
    hint: "Think about what's on top during different seasons...",
    points: 30,
  },
  {
    id: "rid-2",
    type: "riddle",
    title: "River Riddle",
    emoji: "🌊",
    content: "I run downhill without legs, I roar without a mouth, I carry rocks without hands. The fish love me and the mountains made me. What am I?",
    answer: "A river!",
    hint: "You'll see a lot of me along the Icefields Parkway...",
    points: 30,
  },
  {
    id: "rid-3",
    type: "riddle",
    title: "Bear Riddle",
    emoji: "🐻",
    content: "I sleep through the cold, I eat all summer long, I have a hump on my back but I'm no camel, and park wardens put up signs warning you about me. What am I?",
    answer: "A grizzly bear!",
    hint: "You'll want to make noise while hiking in Banff to avoid surprising one...",
    points: 30,
  },
  {
    id: "rid-4",
    type: "riddle",
    title: "Ice Riddle",
    emoji: "🧊",
    content: "I'm made of snow but I'm not a snowman. I move but I'm not alive. I'm thousands of years old but I'm slowly shrinking. I colour lakes with my dust. What am I?",
    answer: "A glacier!",
    hint: "The Athabasca one is famous...",
    points: 30,
  },
  {
    id: "rid-5",
    type: "riddle",
    title: "Road Riddle",
    emoji: "🛣️",
    content: "I go from Banff to Jasper, I'm called a Parkway, I pass a hundred glaciers but I'm never cold, and I'm considered one of the world's most beautiful roads. What am I?",
    answer: "The Icefields Parkway!",
    hint: "Highway 93...",
    points: 30,
  },
  {
    id: "rid-6",
    type: "riddle",
    title: "Forest Riddle",
    emoji: "🌲",
    content: "I have thousands of needles but I've never sewed a thing. I stand in the mountain cold and smell amazing. Moose eat my bark and squirrels love my seeds. What am I?",
    answer: "A pine (or spruce) tree!",
    hint: "Look out the window — you're probably surrounded by me right now...",
    points: 30,
  },
  {
    id: "rid-7",
    type: "riddle",
    title: "Hotel Riddle",
    emoji: "🏰",
    content: "I look like a Scottish castle, I'm one of Canada's most famous buildings, I sit where the Bow and Spray rivers meet, and I've hosted royalty. What am I?",
    answer: "The Banff Springs Hotel!",
    hint: "It was built by the Canadian Pacific Railway in 1888...",
    points: 30,
  },
  {
    id: "rid-8",
    type: "riddle",
    title: "Little Guy Riddle",
    emoji: "🐹",
    content: "I'm tiny and round like a potato with ears. I don't hibernate but I live under rocks. I spend all summer making a secret food pile. A single whistle blast means danger. What am I?",
    answer: "A pika!",
    hint: "They live in rocky alpine slopes and are related to rabbits...",
    points: 30,
  },
  {
    id: "rid-9",
    type: "riddle",
    title: "Water Riddle",
    emoji: "♨️",
    content: "I start as rain on a mountain, sink 3 kilometres underground, get heated for 500 years, then bubble up warm in a rocky pool. People have soaked in me for thousands of years. What am I?",
    answer: "Hot springs!",
    hint: "There are famous ones on Sulphur Mountain in Banff...",
    points: 30,
  },
  {
    id: "rid-10",
    type: "riddle",
    title: "Night Sky Riddle",
    emoji: "🌌",
    content: "I'm brightest where there are no cities, I contain 200 billion suns, and on a clear night in Banff you can see my cloudy arm stretch across the sky. What am I?",
    answer: "The Milky Way galaxy!",
    hint: "Banff is a Dark Sky Preserve — perfect for seeing me...",
    points: 30,
  },

  // ── MORE CONVERSATION STARTERS ────────────────────────────────────────────
  {
    id: "conv-11",
    type: "conversation",
    title: "Worst Car Smell",
    emoji: "👃",
    content: "What's the worst smell you've ever experienced in a car? Describe it in painful detail. The most disgusting story wins.",
    points: 10,
  },
  {
    id: "conv-12",
    type: "conversation",
    title: "Unpopular Opinion",
    emoji: "🤨",
    content: "Name one thing EVERYONE loves that you actually hate. No judgment. Just honesty. Start with: 'I know this is wrong, but...'",
    points: 10,
  },
  {
    id: "conv-13",
    type: "conversation",
    title: "Dream Cabin",
    emoji: "🏡",
    content: "You own a cabin in the Rockies. Describe it in 60 seconds: where is it, what does it look like inside, and what's the one house rule?",
    points: 10,
  },
  {
    id: "conv-14",
    type: "conversation",
    title: "Secret Talent",
    emoji: "🎩",
    content: "Confess a weird or embarrassing hidden talent. The stranger the better. Everyone has to share one — no getting out of it.",
    points: 10,
  },
  {
    id: "conv-15",
    type: "conversation",
    title: "If Animals Could Talk",
    emoji: "🦊",
    content: "If a Banff animal could speak to you right now, what would it say? Pick an animal — bear, elk, pika, marmot, wolf — and give it one sentence.",
    points: 10,
  },
  {
    id: "conv-16",
    type: "conversation",
    title: "Road Trip Role",
    emoji: "🗺️",
    content: "Every road trip has characters: the Navigator, the Snack Captain, the DJ, the Photographer, the Complainer. Which one are you RIGHT NOW? Be honest.",
    points: 10,
  },
  {
    id: "conv-17",
    type: "conversation",
    title: "Mountain vs Ocean",
    emoji: "🌊",
    content: "Mountains or ocean? You can only vacation in ONE for the rest of your life. Make your case in 30 seconds. Then vote.",
    points: 10,
  },
  {
    id: "conv-18",
    type: "conversation",
    title: "Childhood Trip",
    emoji: "👶",
    content: "What's the earliest family trip memory you have? It can be tiny — a smell, a sound, a rest stop toy. Whoever shares first gets to pick the next snack.",
    points: 10,
  },
  {
    id: "conv-19",
    type: "conversation",
    title: "Rename the Car",
    emoji: "🚗",
    content: "Our car needs an official road trip name. Nominate one name each with a reason, then vote. The winning name is law for the rest of the trip.",
    points: 10,
  },
  {
    id: "conv-20",
    type: "conversation",
    title: "One Thing To Leave Behind",
    emoji: "🗑️",
    content: "If you could permanently delete one thing from road trips — traffic, bad rest stop food, car sickness, backseat arguments — what goes and why?",
    points: 10,
  },
  {
    id: "conv-21",
    type: "conversation",
    title: "Hiking Confession",
    emoji: "🥾",
    content: "Have you ever quit a hike, taken a wrong trail, or gotten totally lost? Story time. Bonus points if it ended with food.",
    points: 10,
  },
  {
    id: "conv-22",
    type: "conversation",
    title: "Future Trip",
    emoji: "🌍",
    content: "Where should the next big family trip be? Everyone pitches one destination with a one-sentence sell. Then a quick vote.",
    points: 10,
  },
  {
    id: "conv-23",
    type: "conversation",
    title: "Star of the Trip",
    emoji: "⭐",
    content: "Who in this car would survive longest in the wilderness, and who would complain themselves to safety? Honest answers only.",
    points: 10,
  },
  {
    id: "conv-24",
    type: "conversation",
    title: "Park Rules",
    emoji: "📜",
    content: "You're in charge of Banff. You can add ONE rule and remove ONE rule. What changes?",
    points: 10,
  },
  {
    id: "conv-25",
    type: "conversation",
    title: "This Moment",
    emoji: "🌅",
    content: "Everyone look out the window for 10 seconds. Without looking at your phone, describe what you just saw in one sentence. Go.",
    points: 10,
  },

  // ── MORE FACTS ─────────────────────────────────────────────────────────────
  {
    id: "fact-11",
    type: "fact",
    title: "Hoodoo Mystery",
    emoji: "🗿",
    content: "The Hoodoos near Banff are strange mushroom-shaped rock towers created by erosion. Softer rock wears away around a harder cap, leaving pillars up to 7 metres tall. Indigenous peoples historically called them home to spirits.",
    points: 5,
  },
  {
    id: "fact-12",
    type: "fact",
    title: "Lynx Power",
    emoji: "🐱",
    content: "Canada lynx have enormous paws that act like natural snowshoes. Each paw spreads out to be wider than a man's hand, letting them run across deep snow where prey like snowshoe hares sink in.",
    points: 5,
  },
  {
    id: "fact-13",
    type: "fact",
    title: "Banff Ave History",
    emoji: "🏘️",
    content: "Banff Avenue was once a bustling railway stop street — the Canadian Pacific Railway literally built it to bring wealthy tourists west in the 1880s. The whole town was essentially designed as a tourist resort from day one.",
    points: 5,
  },
  {
    id: "fact-14",
    type: "fact",
    title: "Bighorn Horns",
    emoji: "🐏",
    content: "A bighorn sheep's horns can weigh up to 14 kg — that's more than ALL the bones in the rest of its body combined. Rams charge each other at 32 km/h and the CRACK can be heard over a kilometre away.",
    points: 5,
  },
  {
    id: "fact-15",
    type: "fact",
    title: "Bow Lake",
    emoji: "💧",
    content: "Bow Lake is the source of the Bow River, which flows through Banff, Calgary, and eventually into Hudson Bay thousands of kilometres away. Every drop in that lake ends up in the Atlantic Ocean.",
    points: 5,
  },
  {
    id: "fact-16",
    type: "fact",
    title: "Wolverine Fury",
    emoji: "😤",
    content: "The wolverine — Canada's most ferocious animal for its size — can drive a grizzly bear off a kill. They weigh only 13 kg but have been documented fighting off cougars and wolves. Pound for pound, the most aggressive land animal in North America.",
    points: 5,
  },
  {
    id: "fact-17",
    type: "fact",
    title: "Columbia Icefield",
    emoji: "🧊",
    content: "The Columbia Icefield is the largest icefield in the Rocky Mountains south of Alaska. It covers 325 km² — about the size of Edmonton. It feeds SIX major river systems and drains into three different oceans.",
    points: 5,
  },
  {
    id: "fact-18",
    type: "fact",
    title: "Northern Lights",
    emoji: "🌌",
    content: "The Northern Lights (Aurora Borealis) are caused by solar particles hitting Earth's atmosphere. In Banff, they're visible 20–30 nights per year — especially in fall and winter. June nights can show them too, though the short night makes it rare.",
    points: 5,
  },
  {
    id: "fact-19",
    type: "fact",
    title: "Wolf Packs",
    emoji: "🐺",
    content: "Wolf packs in Banff have territories of up to 2,000 km². A pack typically covers that entire area in one to two weeks. They've been seen on security cameras using the wildlife overpasses on Highway 1 regularly.",
    points: 5,
  },
  {
    id: "fact-20",
    type: "fact",
    title: "Sulphur Mountain Tram",
    emoji: "🚡",
    content: "The Banff Gondola takes you to the summit of Sulphur Mountain (2,281 m) in 8 minutes — a climb that would take 2 hours on foot. From the top you can see six mountain ranges on a clear day.",
    points: 5,
  },
  {
    id: "fact-21",
    type: "fact",
    title: "Moraine Lake",
    emoji: "🏔️",
    content: "Moraine Lake's colour is even more intense than Lake Louise. It was on the back of the Canadian $20 bill from 1969 to 1979. The 'Valley of the Ten Peaks' viewpoint behind it is considered one of the most photographed spots in Canada.",
    points: 5,
  },
  {
    id: "fact-22",
    type: "fact",
    title: "Peyto Lake Fox",
    emoji: "🦊",
    content: "Peyto Lake is named after Bill Peyto, an eccentric early Banff guide who once kept a lynx as a pet and showed up to his own rescue party to see what the fuss was about. His ashes were scattered in the park he loved.",
    points: 5,
  },
  {
    id: "fact-23",
    type: "fact",
    title: "Avalanche Science",
    emoji: "❄️",
    content: "Banff Parks Canada staff intentionally trigger avalanches on dangerous slopes — usually with artillery shells or explosives — to make highways and ski areas safe. They've been doing controlled avalanche blasting since 1961.",
    points: 5,
  },
  {
    id: "fact-24",
    type: "fact",
    title: "Banff Springs Pool",
    emoji: "🏊",
    content: "The Banff Springs Hotel has a ghost — the 'Bride of Banff Springs' allegedly haunts the sixth floor after falling down the staircase on her wedding day. Hotel staff have reported seeing a figure dancing alone in the ballroom.",
    points: 5,
  },
  {
    id: "fact-25",
    type: "fact",
    title: "Cougar Country",
    emoji: "🐆",
    content: "Cougars (mountain lions) live in Banff but are almost never seen. They can leap 6 metres horizontally and 3 metres straight up from standing. If you see one, make yourself look BIG — never run. They respond to flight instinct.",
    points: 5,
  },

  // ── MORE TRUE / FALSE ──────────────────────────────────────────────────────
  {
    id: "tf-11",
    type: "trueFalse",
    title: "Elk Antlers",
    emoji: "🦌",
    content: "Male elk (bulls) grow and shed their antlers every single year.",
    answer: "true",
    hint: "Antlers grow back each spring — they're the fastest-growing tissue in the animal kingdom, growing up to 2.5 cm per day!",
    points: 15,
  },
  {
    id: "tf-12",
    type: "trueFalse",
    title: "Banff Altitude",
    emoji: "🏔️",
    content: "Banff townsite sits at a higher elevation than Calgary.",
    answer: "true",
    hint: "Calgary is at ~1,045 m. Banff is at 1,383 m — about 300 metres higher.",
    points: 15,
  },
  {
    id: "tf-13",
    type: "trueFalse",
    title: "Black Bear Colour",
    emoji: "🐻",
    content: "All black bears in Banff are black in colour.",
    answer: "false",
    hint: "Black bears can be black, brown, cinnamon, or even blonde! The name refers to the species, not the colour.",
    points: 15,
  },
  {
    id: "tf-14",
    type: "trueFalse",
    title: "Hummingbirds",
    emoji: "🐦",
    content: "Hummingbirds can be found in Banff National Park during summer.",
    answer: "true",
    hint: "The Rufous Hummingbird migrates through the Canadian Rockies each summer, feeding on wildflowers at elevation.",
    points: 15,
  },
  {
    id: "tf-15",
    type: "trueFalse",
    title: "Lake Temperature",
    emoji: "🌡️",
    content: "Lake Louise and Moraine Lake never fully freeze in winter.",
    answer: "false",
    hint: "Both lakes freeze solid in winter. Lake Louise is used for ice skating! The ice can be over a metre thick.",
    points: 15,
  },
  {
    id: "tf-16",
    type: "trueFalse",
    title: "Grizzly Grubs",
    emoji: "🐛",
    content: "Grizzly bears eat mostly meat — they're top predators, after all.",
    answer: "false",
    hint: "Up to 90% of a grizzly's diet is plants, berries, roots, and insects! They eat far more vegetation than meat. The term is 'omnivore' but they skew herbivore.",
    points: 15,
  },
  {
    id: "tf-17",
    type: "trueFalse",
    title: "Park Dogs",
    emoji: "🐕",
    content: "Dogs are allowed on all trails in Banff National Park.",
    answer: "false",
    hint: "Dogs are NOT allowed on many trails in Banff — especially in wildlife corridors. Where allowed, they must be leashed. Check trail rules before hiking with a dog!",
    points: 15,
  },
  {
    id: "tf-18",
    type: "trueFalse",
    title: "Mountain Goat Range",
    emoji: "🐐",
    content: "Mountain goats are native to the Canadian Rockies.",
    answer: "true",
    hint: "Mountain goats are the only large mammal that stays at high elevation year-round. They prefer cliffs and rocky terrain above the treeline.",
    points: 15,
  },
  {
    id: "tf-19",
    type: "trueFalse",
    title: "Wildfire Role",
    emoji: "🔥",
    content: "Wildfires are purely destructive in Banff National Park and Parks Canada tries to prevent all of them.",
    answer: "false",
    hint: "Parks Canada now uses controlled burns intentionally — fire is a natural part of the ecosystem that clears dead wood and encourages new growth. Some areas NEED periodic fire to stay healthy.",
    points: 15,
  },
  {
    id: "tf-20",
    type: "trueFalse",
    title: "Banff Borders",
    emoji: "🗺️",
    content: "Banff National Park shares a border with Jasper National Park to the north.",
    answer: "true",
    hint: "Together, Banff and Jasper (along with Yoho and Kootenay) form a UNESCO World Heritage Site — one of the largest protected mountain areas in the world.",
    points: 15,
  },
  {
    id: "tf-21",
    type: "trueFalse",
    title: "Fish in Altitude",
    emoji: "🐟",
    content: "Fish can survive in glacier-fed mountain lakes like Lake Louise.",
    answer: "true",
    hint: "Lake Louise has been stocked with fish historically. Cold-water species like lake trout and bull trout thrive in glacial lakes.",
    points: 15,
  },
  {
    id: "tf-22",
    type: "trueFalse",
    title: "Speed of Sound",
    emoji: "💨",
    content: "You can hear a gunshot-style sound from bighorn rams clashing horns from over 1 km away.",
    answer: "true",
    hint: "Rams clash at up to 32 km/h and the impact creates a crack that echoes off rock faces for kilometres. It's one of the loudest natural sounds in the Rockies.",
    points: 15,
  },
  {
    id: "tf-23",
    type: "trueFalse",
    title: "Bear Spray Scent",
    emoji: "🌶️",
    content: "Bears are attracted to the smell of used bear spray, so you should spray it around your campsite to deter them.",
    answer: "false",
    hint: "CRITICAL: DO NOT spray bear spray around your campsite! Bears are attracted to the residue. Bear spray is ONLY for direct use when a bear is charging you.",
    points: 15,
  },
  {
    id: "tf-24",
    type: "trueFalse",
    title: "Tunnel Mountain",
    emoji: "⛏️",
    content: "Tunnel Mountain in Banff actually has a tunnel through it.",
    answer: "false",
    hint: "Tunnel Mountain has no tunnel! It was named because railway engineers originally planned a tunnel there, then changed the route. The tunnel was never built.",
    points: 15,
  },
  {
    id: "tf-25",
    type: "trueFalse",
    title: "Trans-Canada",
    emoji: "🛣️",
    content: "The Trans-Canada Highway (Highway 1) runs directly through Banff National Park.",
    answer: "true",
    hint: "The Trans-Canada cuts straight through the park — which is why Banff has those 38 wildlife crossings. It's one of the highest-traffic sections of any national park road in the world.",
    points: 15,
  },

  // ── MORE QUIZZES ───────────────────────────────────────────────────────────
  {
    id: "quiz-11",
    type: "quiz",
    title: "Peyto Lake",
    emoji: "🦊",
    content: "Peyto Lake appears to glow neon blue-green from above. What shape do people say it resembles when viewed from the lookout?",
    options: ["A howling wolf", "A running fox", "A crouching cat", "A swimming beaver"],
    answer: "A howling wolf",
    hint: "Look at it on a map — the turquoise 'head' of the lake really does look like a wolf.",
    points: 20,
  },
  {
    id: "quiz-12",
    type: "quiz",
    title: "Grizzly Count",
    emoji: "🐻",
    content: "Roughly how many grizzly bears live in Banff National Park?",
    options: ["About 60", "About 200", "About 500", "Over 1,000"],
    answer: "About 60",
    hint: "The Banff grizzly population is small and carefully monitored. Each bear has a name and is tracked by Parks Canada.",
    points: 20,
  },
  {
    id: "quiz-13",
    type: "quiz",
    title: "Gondola Summit",
    emoji: "🚡",
    content: "What is the name of the mountain the Banff Gondola takes you to the top of?",
    options: ["Cascade Mountain", "Mount Norquay", "Sulphur Mountain", "Mount Rundle"],
    answer: "Sulphur Mountain",
    hint: "It's named for the hot springs on its slopes — you can smell the sulfur!",
    points: 20,
  },
  {
    id: "quiz-14",
    type: "quiz",
    title: "Trans-Canada Wildlife",
    emoji: "🐾",
    content: "How many wildlife crossing structures (overpasses and underpasses) are along the Trans-Canada in Banff?",
    options: ["6", "14", "38", "52"],
    answer: "38",
    hint: "It's the most of any national park in the world, and they've recorded over 200,000 animal crossings!",
    points: 20,
  },
  {
    id: "quiz-15",
    type: "quiz",
    title: "Icefields Parkway Length",
    emoji: "📏",
    content: "How long is the Icefields Parkway (Highway 93) from Banff to Jasper?",
    options: ["93 km", "145 km", "232 km", "310 km"],
    answer: "232 km",
    hint: "It was named Highway 93 — but the road itself is 232 km of pure mountain scenery.",
    points: 20,
  },
  {
    id: "quiz-16",
    type: "quiz",
    title: "Rockies Formation",
    emoji: "🌍",
    content: "How were the Canadian Rockies formed?",
    options: [
      "Volcanic eruptions pushed rock upward",
      "Tectonic plates collided, buckling layers of seafloor rock",
      "A meteor impact cracked the ground",
      "Glaciers carved the rock upward over millions of years",
    ],
    answer: "Tectonic plates collided, buckling layers of seafloor rock",
    hint: "The Rockies were once a shallow sea! Plate collision crumpled the seabed into mountains.",
    points: 20,
  },
  {
    id: "quiz-17",
    type: "quiz",
    title: "Banff Spring Hotel Age",
    emoji: "🏰",
    content: "In approximately what year did the Banff Springs Hotel first open?",
    options: ["1860", "1888", "1920", "1945"],
    answer: "1888",
    hint: "It was built by the Canadian Pacific Railway when the train line first reached Banff.",
    points: 20,
  },
  {
    id: "quiz-18",
    type: "quiz",
    title: "Moose Facts",
    emoji: "🫎",
    content: "What do moose primarily eat?",
    options: ["Fish and small mammals", "Aquatic plants, twigs, and bark", "Grass and ground-level plants only", "Berries and nuts like bears"],
    answer: "Aquatic plants, twigs, and bark",
    hint: "Moose are uniquely adapted to wade into lakes and rivers to eat underwater plants. Their long legs make wading easy!",
    points: 20,
  },
  {
    id: "quiz-19",
    type: "quiz",
    title: "First Nations",
    emoji: "🪶",
    content: "Which First Nations people have historically called the Banff area home for thousands of years?",
    options: [
      "Only the Blackfoot Confederacy",
      "The Stoney Nakoda, Blackfoot, and other Nations",
      "The Haida and Coast Salish peoples",
      "No Indigenous peoples — it was too mountainous",
    ],
    answer: "The Stoney Nakoda, Blackfoot, and other Nations",
    hint: "The Banff area was a meeting place and seasonal hunting ground for multiple First Nations for at least 10,000 years before the park was created.",
    points: 20,
  },
  {
    id: "quiz-20",
    type: "quiz",
    title: "Glacial Retreat",
    emoji: "📉",
    content: "The Athabasca Glacier (near Banff on the Icefields Parkway) has retreated by approximately how much since 1870?",
    options: ["100 metres", "500 metres", "1.5 kilometres", "5 kilometres"],
    answer: "1.5 kilometres",
    hint: "Marker posts along the viewing path show where the glacier's edge was in different decades. The retreat is dramatic and visible.",
    points: 20,
  },
  {
    id: "quiz-21",
    type: "quiz",
    title: "Wolves and Elk",
    emoji: "🐺",
    content: "When wolves were reintroduced / returned to Banff in the 1980s-90s, what unexpected ecological effect did they have?",
    options: [
      "They wiped out the elk completely",
      "They caused rivers to change course by reducing elk overgrazing",
      "They scared away all the grizzly bears",
      "Nothing significant changed",
    ],
    answer: "They caused rivers to change course by reducing elk overgrazing",
    hint: "This is called a 'trophic cascade.' Wolves scared elk away from riverbanks, which let vegetation regrow, which stabilized riverbanks, which changed river paths.",
    points: 20,
  },
  {
    id: "quiz-22",
    type: "quiz",
    title: "Rocky Rockies",
    emoji: "🪨",
    content: "What type of rock makes up most of the Canadian Rockies peaks?",
    options: ["Granite", "Basalt", "Limestone and shale", "Sandstone"],
    answer: "Limestone and shale",
    hint: "These are sedimentary rocks — formed at the bottom of ancient seas. You can often see the horizontal layering on cliff faces.",
    points: 20,
  },
  {
    id: "quiz-23",
    type: "quiz",
    title: "Banff Town Ownership",
    emoji: "🏛️",
    content: "Who technically owns the land that Banff townsite sits on?",
    options: [
      "The Province of Alberta",
      "The Town of Banff municipality",
      "The Federal Government of Canada",
      "The Canadian Pacific Railway",
    ],
    answer: "The Federal Government of Canada",
    hint: "Because it's in a national park, the federal government owns the land. Residents and businesses lease their land from the Crown — they don't own it outright.",
    points: 20,
  },
  {
    id: "quiz-24",
    type: "quiz",
    title: "Mountain Goat Babies",
    emoji: "🐐",
    content: "What are baby mountain goats called?",
    options: ["Calves", "Kits", "Kids", "Fawns"],
    answer: "Kids",
    hint: "Same as domestic goats! Mountain goat kids can walk and jump on rocky terrain within hours of being born.",
    points: 20,
  },
  {
    id: "quiz-25",
    type: "quiz",
    title: "UV at Altitude",
    emoji: "☀️",
    content: "How much stronger is UV radiation at 2,000 m elevation compared to sea level?",
    options: ["About the same", "10% stronger", "25–50% stronger", "3× stronger"],
    answer: "25–50% stronger",
    hint: "Less atmosphere = less UV protection. Sunburn happens fast in the Rockies even on cloudy days. Sunscreen is not optional!",
    points: 20,
  },

  // ── MORE GAMES ─────────────────────────────────────────────────────────────
  {
    id: "game-11",
    type: "game",
    title: "Two Truths, One Lie",
    emoji: "🤥",
    content: "Each person shares TWO true things about themselves and ONE lie, in any order. Everyone else guesses which is the lie. Keep score — one point for each person you fool, one point for each lie you catch.",
    points: 25,
  },
  {
    id: "game-12",
    type: "game",
    title: "Fortunately / Unfortunately",
    emoji: "🎭",
    content: "Tell a story going around the car. Alternate between 'Fortunately...' and 'Unfortunately...' sentences. Start: 'We were driving through Banff when fortunately a grizzly bear gave us directions...' Take turns!",
    points: 25,
  },
  {
    id: "game-13",
    type: "game",
    title: "One Word Story",
    emoji: "✍️",
    content: "Build a story — but each person can only say ONE word at a time. Go around fast. No pausing. Try to keep it coherent… or don't. Either way is fun.",
    points: 25,
  },
  {
    id: "game-14",
    type: "game",
    title: "Geography Chain",
    emoji: "🌐",
    content: "Name a place — city, country, mountain, lake, anything. The next person names a place starting with the LAST letter of that place. No repeating! (Banff → Fiji → Iceland → Denmark...)",
    points: 25,
  },
  {
    id: "game-15",
    type: "game",
    title: "Speed Counting",
    emoji: "🔢",
    content: "Count from 1 to 100 as a group — but every multiple of 7 must be replaced with 'MOUNTAIN' and every multiple of 5 with 'BEAR.' Miss one and you start over. Warning: this gets hard fast.",
    points: 25,
  },
  {
    id: "game-16",
    type: "game",
    title: "Who Am I?",
    emoji: "🎭",
    content: "Think of a famous person or character. Everyone else asks YES/NO questions to figure out who you are — you can only answer yes, no, or sometimes. Clue limit: 20 questions. If they guess, pick a new person.",
    points: 25,
  },
  {
    id: "game-17",
    type: "game",
    title: "Rhyme Battle",
    emoji: "🎤",
    content: "Pick a word. Go around the car rhyming. No repeating, no made-up words. Last person to rhyme wins. Start word: BEAR. Ready? GO.",
    points: 25,
  },
  {
    id: "game-18",
    type: "game",
    title: "Categories Sprint",
    emoji: "⚡",
    content: "Pick a category (e.g. 'animals that live in Canada'). Go around and name something from that category without repeating. Hesitate for more than 3 seconds and you're out. Last one naming wins.",
    points: 25,
  },
  {
    id: "game-19",
    type: "game",
    title: "Emoji Story",
    emoji: "📱",
    content: "Someone picks 5 random emojis from their phone keyboard. Everyone else has 60 seconds to invent a story using ALL five emojis. The funniest story wins. No re-picking emojis!",
    points: 25,
  },
  {
    id: "game-20",
    type: "game",
    title: "Best/Worst",
    emoji: "🏆",
    content: "Take turns finishing this sentence: 'The best thing about [topic] is ___ and the worst thing is ___.' Topics: this car, bears, Banff, road trips, mountains. Everyone answers each topic.",
    points: 25,
  },
  {
    id: "game-21",
    type: "game",
    title: "Debate Club",
    emoji: "⚖️",
    content: "Topic: 'Hiking is better than swimming.' Two people debate — one FOR, one AGAINST — for 60 seconds each. Everyone else votes after. Next round: 'Mountains are better than beaches.'",
    points: 25,
  },
  {
    id: "game-22",
    type: "game",
    title: "Guess My Number",
    emoji: "🔢",
    content: "One person picks a number between 1 and 100. Others guess — after each guess, say 'higher' or 'lower.' Count how many guesses it takes. The person who guesses in the fewest tries wins next round.",
    points: 25,
  },
  {
    id: "game-23",
    type: "game",
    title: "Backward Spelling",
    emoji: "🔄",
    content: "Someone says a word — the next person must spell it BACKWARDS out loud. Start easy (cat = t-a-c), then get harder. Try: MOUNTAIN, GLACIER, BANFF, WILDERNESS. No phones!",
    points: 25,
  },
  {
    id: "game-24",
    type: "game",
    title: "Rapid Fire Questions",
    emoji: "💨",
    content: "One person is the 'hot seat.' Everyone fires questions at them for 60 seconds — they must answer IMMEDIATELY, no thinking. Best answers: fast, weird, honest. Rotate who's in the hot seat.",
    points: 25,
  },
  {
    id: "game-25",
    type: "game",
    title: "The Compliment Chain",
    emoji: "💛",
    content: "Go around the car. Each person gives the next person a genuine compliment — but it must be about something that happened ON THIS TRIP. Keep going until everyone has given and received one.",
    points: 25,
  },

  // ── MORE RIDDLES ───────────────────────────────────────────────────────────
  {
    id: "rid-11",
    type: "riddle",
    title: "Wildlife Riddle",
    emoji: "🦌",
    content: "I have a crown but I'm not a king. I shed it every year but I'm not losing my mind. I bugle in autumn but I'm not a musician. Rangers put up signs when I'm feeling romantic. What am I?",
    answer: "An elk (bull elk)!",
    hint: "The 'crown' is antlers, the 'bugle' is a mating call, and the signs warn hikers during rut season...",
    points: 30,
  },
  {
    id: "rid-12",
    type: "riddle",
    title: "Invisible Riddle",
    emoji: "💨",
    content: "I travel through mountains but leave no footprints. I push the pine trees side to side. I whistle through your car windows and I can be freezing in June. What am I?",
    answer: "Wind!",
    hint: "You can feel it but you can't see it...",
    points: 30,
  },
  {
    id: "rid-13",
    type: "riddle",
    title: "Shadow Riddle",
    emoji: "🌤️",
    content: "I grow in the morning, shrink at noon, then grow again. Mountains make me dramatic. At sunset I stretch across valleys for kilometres. What am I?",
    answer: "A shadow!",
    hint: "It's about the position of the sun...",
    points: 30,
  },
  {
    id: "rid-14",
    type: "riddle",
    title: "Tiny Giant",
    emoji: "🐿️",
    content: "I'm smaller than a cat but I never stop running. I alarm the whole forest when danger comes. I store more than my body weight in food every fall. My cheeks can stretch to three times their size. What am I?",
    answer: "A chipmunk!",
    hint: "Those stuffed cheeks are full of seeds for winter...",
    points: 30,
  },
  {
    id: "rid-15",
    type: "riddle",
    title: "Ancient Traveller",
    emoji: "🦋",
    content: "I weigh less than a paperclip, I fly thousands of kilometres in autumn, I navigate with the sun, and somehow I find the same tree my great-great-grandmother used — even though I've never been there. What am I?",
    answer: "A monarch butterfly!",
    hint: "They migrate through the Rockies to Mexico — with no GPS and no parents to follow...",
    points: 30,
  },
  {
    id: "rid-16",
    type: "riddle",
    title: "Old But Alive",
    emoji: "🌲",
    content: "I can live for over a thousand years. I don't have a brain but I know when to drop my leaves. I don't have legs but I walk slowly across hillsides over centuries. What am I?",
    answer: "A tree!",
    hint: "Forests do slowly move uphill as climates warm — it just takes generations to see...",
    points: 30,
  },
  {
    id: "rid-17",
    type: "riddle",
    title: "Car Riddle",
    emoji: "🚗",
    content: "I hold a family, I eat fuel, I love highways but hate potholes. I've driven through some of the most beautiful scenery on Earth this week and nobody thanked me. What am I?",
    answer: "Your car!",
    hint: "Look around you...",
    points: 30,
  },
  {
    id: "rid-18",
    type: "riddle",
    title: "Mountain Echo",
    emoji: "📢",
    content: "You make me but you can't keep me. You send me out and I come back to find you. In mountains I bounce around longer than anywhere else. Shout in a canyon and I'll repeat your words. What am I?",
    answer: "An echo!",
    hint: "Try it in a valley in Banff...",
    points: 30,
  },
  {
    id: "rid-19",
    type: "riddle",
    title: "Always Hungry",
    emoji: "🌀",
    content: "I'm always hungry and must be fed. Whatever I eat, I leave behind in red, orange, and grey. I have no mouth, yet I devour everything. Firefighters both fear me and sometimes start me on purpose. What am I?",
    answer: "Fire!",
    hint: "Parks Canada does controlled burns to help the ecosystem...",
    points: 30,
  },
  {
    id: "rid-20",
    type: "riddle",
    title: "Map Riddle",
    emoji: "🗺️",
    content: "I can show you every trail in Banff but I never hike them. I can show you where the bears are but I never smell them. I fit in your pocket but I contain thousands of kilometres. What am I?",
    answer: "A map!",
    hint: "Old school or on your phone — same answer...",
    points: 30,
  },
  {
    id: "rid-21",
    type: "riddle",
    title: "Cold Comfort",
    emoji: "🧊",
    content: "I'm colder than your fridge and older than your great-grandparents. I make lakes turquoise. I'm a river that moves in slow motion. Scientists measure my retreat in metres per year. What am I?",
    answer: "A glacier!",
    hint: "We have a different riddle about this — but this one's from a different angle...",
    points: 30,
  },
  {
    id: "rid-22",
    type: "riddle",
    title: "Night Puzzle",
    emoji: "🌙",
    content: "I appear every night but never twice the same. I'm made of gas and dust from billions of years ago. In Banff you can see me in my full glory without city lights. I am not one thing — I am 200 billion things. What am I?",
    answer: "The stars (or the Milky Way)!",
    hint: "Banff is a Dark Sky Preserve for a reason...",
    points: 30,
  },
  {
    id: "rid-23",
    type: "riddle",
    title: "The Clever Thief",
    emoji: "🐦",
    content: "I steal your lunch if you leave it unattended. I'm black and grey and smarter than I look. I've learned to unzip backpacks. Hikers curse me but secretly love me. I'm a bird, not a bear. What am I?",
    answer: "A Canada Jay (also called Whiskey Jack or Camp Robber)!",
    hint: "They're known for stealing food from campsites — hence the nickname 'Camp Robber.'",
    points: 30,
  },
  {
    id: "rid-24",
    type: "riddle",
    title: "The Invisible Bridge",
    emoji: "🌈",
    content: "I have no weight but I carry colours. I appear after rain and disappear when I try to be touched. I arch over Banff valleys on the most dramatic days. What am I?",
    answer: "A rainbow!",
    hint: "Mountain rain showers make for spectacular rainbows...",
    points: 30,
  },
  {
    id: "rid-25",
    type: "riddle",
    title: "Family Riddle",
    emoji: "👨‍👩‍👧‍👦",
    content: "I contain everyone in this car. I create memories you'll tell for 20 years. I argue, laughs, and gets carsick sometimes. I'm the reason this trip matters. What am I?",
    answer: "Your family!",
    hint: "Look around the car...",
    points: 30,
  },

  // ── RHYME TIME ────────────────────────────────────────────────────────────
  {
    id: "rhyme-1",
    type: "rhyme",
    title: "Mountain Rap",
    emoji: "🎤",
    content: "Freestyle rap about what you see out the window RIGHT NOW. You have 10 seconds to start, then go. Minimum 4 lines. Everyone rates it 1–10.",
    hint: "\"We're rolling through the mountains, the peaks are so tall / The trees are getting bigger as we're having a ball...\"",
    points: 20,
  },
  {
    id: "rhyme-2",
    type: "rhyme",
    title: "Complete the Couplet",
    emoji: "✍️",
    content: "Finish this couplet — everyone writes or says their own ending, then vote on the best:\n\n\"We packed the car with snacks and gear,\nAnd set off on a trip that's...\"",
    hint: "\"...once a year\" / \"...full of cheer\" / \"...crystal clear\"",
    points: 20,
  },
  {
    id: "rhyme-3",
    type: "rhyme",
    title: "Bear Limerick",
    emoji: "🐻",
    content: "Complete this limerick together — one person per line, in order:\n\nLine 1: \"There once was a bear on a trail\"\nLine 2 (rhymes with trail): ___\nLine 3 (short): ___\nLine 4 (short, rhymes with 3): ___\nLine 5 (rhymes with trail): ___",
    hint: "Line 2: \"Who wagged his enormous brown tail\" / Line 3: \"He sniffed at our pack\" / Line 4: \"And wanted a snack\" / Line 5: \"Then waddled away down the vale\"",
    points: 20,
  },
  {
    id: "rhyme-4",
    type: "rhyme",
    title: "Rhyme Chain",
    emoji: "🔗",
    content: "Start word: ROAD\n\nGo around the car — each person says a word that rhymes. No repeating, no hesitating more than 3 seconds. When someone fails, start again with a new word.\n\nBonus words to try: MOUNTAIN, BEAR, LAKE, TREE",
    hint: "Road → toad → load → code → node → owed → bowed... MOUNTAIN is brutal. Good luck.",
    points: 20,
  },
  {
    id: "rhyme-5",
    type: "rhyme",
    title: "Road Trip Haiku",
    emoji: "🌸",
    content: "Everyone writes a road trip haiku — 3 lines, 5 syllables / 7 syllables / 5 syllables. You have 90 seconds. Read them aloud and vote on the best one.\n\nTheme: this moment, right now, in this car.",
    hint: "\"Trees blur past the glass / (5) Someone ate the last good snack / (7) We press on in peace\" (5)",
    points: 20,
  },
  {
    id: "rhyme-6",
    type: "rhyme",
    title: "Finish My Verse",
    emoji: "📝",
    content: "One person starts a verse — 2 lines. The next person adds 2 more lines that rhyme with the first. Keep building until it falls apart or becomes a masterpiece.\n\nOpener: \"The mountains are calling, the road stretches on,\nWe left in the morning before the first dawn...\"",
    hint: "\"The coffee is cold but our spirits are warm, / We're chasing the sunset before the next storm...\"",
    points: 20,
  },
  {
    id: "rhyme-7",
    type: "rhyme",
    title: "Worst Rhyme Wins",
    emoji: "💀",
    content: "This round: the WORST rhyme wins. Everyone has to finish this line as badly as possible:\n\n\"The glacier was blue and the mountains were tall...\"\n\nVote for the most groan-worthy ending. Bad rhymes and forced meter encouraged.",
    hint: "\"...and someone forgot to pack socks after all\" / \"...we drove past a moose near a food court at the mall\"",
    points: 20,
  },
  {
    id: "rhyme-8",
    type: "rhyme",
    title: "The Car Song",
    emoji: "🎵",
    content: "Together, write one verse of an original song about this trip — sung to any tune you already know. It must mention at least 3 real things from this trip (places, people, food, moments). Perform it.",
    hint: "Try it to the tune of \"Take Me Home, Country Roads\" or \"We Will Rock You\" — the rhythms are forgiving.",
    points: 20,
  },
  {
    id: "rhyme-9",
    type: "rhyme",
    title: "Scenic Sonnet (Lazy Edition)",
    emoji: "🖊️",
    content: "You only need 4 lines — ABAB rhyme scheme. Describe the view outside the window RIGHT NOW. Go around: person 1 does line A, person 2 does line B, person 3 does line A (different rhyme word), person 4 does line B.",
    hint: "\"The highway winds through forests deep (A) / The peaks above are sharp and white (B) / A raven calls, the silence steep (A) / We drive toward the fading light (B)\"",
    points: 20,
  },
  {
    id: "rhyme-10",
    type: "rhyme",
    title: "Name That Rhyme",
    emoji: "🎯",
    content: "One person thinks of a word and gives 3 words that rhyme with it. Everyone else races to guess the original word.\n\nStart simple — then harder. Whoever guesses first picks the next word.",
    hint: "Example: clues are \"gate / late / rate\" → answer is \"eight\" (or wait, bait, hate, etc.) — any word that rhymes with all three!",
    points: 20,
  },
  {
    id: "rhyme-12",
    type: "rhyme",
    title: "Travel Haiku Battle",
    emoji: "⚔️",
    content: "Head-to-head. Two people each write a haiku (5-7-5) about the same subject — picked by a third person. Read aloud, car votes. Best of 3 rounds.\n\nPossible subjects: bears, snacks, traffic, mountains, the backseat.",
    hint: "\"Bear on the roadside / We slowed to a crawl to look / He did not wave back\"",
    points: 20,
  },
  {
    id: "rhyme-13",
    type: "rhyme",
    title: "Alphabet Verse",
    emoji: "🔤",
    content: "Build a poem where each new line starts with the next letter of the alphabet. Go around the car — one line each. Start with A.\n\n\"A — Along the road the mountains rise\"\n\"B — ...\" (your turn)\n\nBonus: keep it about the trip.",
    hint: "\"C — Cold wind blows where glaciers hide / D — Dogs would love it here outside / E — Elk are watching from the ridge...\"",
    points: 20,
  },
  {
    id: "rhyme-14",
    type: "rhyme",
    title: "Snack Rap",
    emoji: "🍿",
    content: "Rap a 4-line verse about the snacks currently in this car. Name at least 3 actual snacks. Beatbox (badly) is encouraged but optional.\n\nEveryone performs theirs. Vote for the best snack rap.",
    hint: "\"Got the chips on deck and the gummies on lock / The granola bars sitting at the back of the stock / We cracked the trail mix somewhere past the pass / This snack situation? Absolutely first class.\"",
    points: 20,
  },
  {
    id: "rhyme-15",
    type: "rhyme",
    title: "Compliment in Verse",
    emoji: "💛",
    content: "Compliment the person to your RIGHT — but it must rhyme, minimum 4 lines, and include at least one specific thing they did on this trip.\n\nEveryone does it at the same time, then reads aloud. Most heartfelt wins.",
    hint: "\"You spotted the eagle when no one else looked / You shared all your snacks without being asked / You read out the facts from the guidebook we brought / And made every long mile feel like it wasn't that taut.\"",
    points: 20,
  },
  {
    id: "rhyme-16",
    type: "rhyme",
    title: "Rocky Road Rap Battle",
    emoji: "🥊",
    content: "Head to head. 30 seconds each. Topic: convince the car that YOUR choice of music/podcast for the next hour is the correct one. It must rhyme. Audience votes.\n\nMay the best verse win.",
    hint: "\"I'm requesting the classics, we need something good / The playlist I built for this drive? Misunderstood. / Give me 30 good minutes and you'll understand / Why my music selection was perfectly planned.\"",
    points: 20,
  },
  {
    id: "rhyme-17",
    type: "rhyme",
    title: "Postcard Poem",
    emoji: "📮",
    content: "Write a 6-line rhyming poem as if it's a postcard from this trip sent to someone at home. Include the destination, one thing you saw, and one thing you ate. Read aloud.\n\nBest postcard gets sent (as a voice memo, text, or actual postcard).",
    hint: "\"Greetings from the mountains, the peaks are all white / We drove through the Rockies from morning to night / The elk by the highway just stared at our car / The hot springs were perfect, the stars brighter by far / The granola bars suffered, the views were divine / Wish you could be here — we're doing just fine.\"",
    points: 20,
  },
  {
    id: "rhyme-18",
    type: "rhyme",
    title: "One-Word Verse",
    emoji: "💬",
    content: "Build a 6-line rhyming poem — but each person can only contribute ONE WORD at a time, going around the car. You cannot plan ahead. You CAN say 'rhyme' words to force the next person into a corner.\n\nSomeone reads it aloud at the end.",
    hint: "This will be incoherent and perfect. That's the point.",
    points: 20,
  },
  {
    id: "rhyme-19",
    type: "rhyme",
    title: "Driver Dedication",
    emoji: "🚗",
    content: "Write and perform a 4-line rhyming tribute to the person driving right now. It must include: their name, one driving habit, and a genuine thank you. It must rhyme. You have 60 seconds.\n\nDriver scores it without looking up from the road.",
    hint: "\"O [name], our captain, who steers through the pass / Who merges so smoothly and never drives fast / Who chose the good playlist and never complains / We thank you for getting us out of those lanes.\"",
    points: 20,
  },
  {
    id: "rhyme-20",
    type: "rhyme",
    title: "Trip Finale Verse",
    emoji: "🌅",
    content: "This is the big one. Everyone writes a 4-line verse about their single favourite moment from the trip so far. Read them aloud in order. No voting — everyone wins this one.\n\nSave them. Read them again in a year.",
    hint: "The best ones will be about tiny things — a joke, a view through rain, a snack eaten at exactly the right moment.",
    points: 20,
  },

  // ── BONUS BANFF ACTIVITIES ────────────────────────────────────────────────
  {
    id: "bonus-1",
    type: "fact",
    title: "Banff Dark Sky",
    emoji: "🌠",
    content: "Banff National Park is a designated Dark Sky Preserve. On a clear night you can see the Milky Way, thousands of stars, and sometimes the Northern Lights. In June, look north after midnight!",
    points: 5,
  },
  {
    id: "bonus-2",
    type: "conversation",
    title: "Trip Traditions",
    emoji: "⭐",
    content: "What should be our official family road trip tradition? Something we do every time — a snack, a stop, a song, a game. Vote and commit!",
    points: 10,
  },
  {
    id: "bonus-3",
    type: "quiz",
    title: "Banff Elevation",
    emoji: "📐",
    content: "What is the elevation of Banff townsite above sea level?",
    options: ["750 m", "1,383 m", "2,000 m", "2,800 m"],
    answer: "1,383 m",
    hint: "That's why some people feel slightly short of breath at first!",
    points: 20,
  },
  {
    id: "bonus-4",
    type: "trueFalse",
    title: "Banff Water",
    emoji: "💧",
    content: "Banff's tap water comes directly from glacial meltwater and is among the cleanest drinking water in the world.",
    answer: "true",
    hint: "Banff gets its water from the Bow River, which is fed by glacier runoff. It's processed and tested — genuinely excellent quality.",
    points: 15,
  },
  {
    id: "bonus-5",
    type: "game",
    title: "Photo Challenge",
    emoji: "📸",
    content: "Everyone takes one photo before the next stop. Theme: 'Most Creative Mountain Shot.' At the next stop, everyone shows their photo. Family vote decides the winner — they pick the next snack stop!",
    points: 25,
  },
  {
    id: "bonus-6",
    type: "conversation",
    title: "Return Trip Dream",
    emoji: "✈️",
    content: "If you could return to Banff with unlimited money and time, what would you do differently? What would you add to this trip right now if you could?",
    points: 10,
  },
  {
    id: "bonus-7",
    type: "riddle",
    title: "The Banff Riddle",
    emoji: "🏔️",
    content: "I'm in a province but also a town. I'm in a park but also a hotel. I'm Canadian but my name comes from a Scottish town. I sit between two rivers in the shadow of Sulphur Mountain. What am I?",
    answer: "Banff!",
    hint: "Named after Banff, Aberdeenshire, Scotland, by CPR president George Stephen...",
    points: 30,
  },
];

// ── HELPERS ────────────────────────────────────────────────────────────────

export function getRandomActivity(excludeIds: string[] = []): Activity {
  const available = activities.filter((a) => !excludeIds.includes(a.id));
  if (available.length === 0) return activities[Math.floor(Math.random() * activities.length)];
  return available[Math.floor(Math.random() * available.length)];
}

export function getActivityById(id: string): Activity | undefined {
  return activities.find((a) => a.id === id);
}

export const TYPE_LABELS: Record<ActivityType, string> = {
  conversation: "Talk It Out",
  fact: "Fun Fact",
  trueFalse: "True or False",
  quiz: "Quiz Time",
  game: "Mini Game",
  riddle: "Riddle Me This",
  rhyme:  "Rhyme Time",
};

export const TYPE_COLORS: Record<ActivityType, string> = {
  conversation: "from-purple-500 to-indigo-600",
  fact: "from-blue-500 to-cyan-600",
  trueFalse: "from-orange-500 to-amber-600",
  quiz: "from-green-500 to-emerald-600",
  game: "from-pink-500 to-rose-600",
  riddle: "from-yellow-500 to-orange-600",
  rhyme:  "from-amber-500 to-orange-500",
};

export const TYPE_BG: Record<ActivityType, string> = {
  conversation: "bg-purple-50 border-purple-200",
  fact: "bg-blue-50 border-blue-200",
  trueFalse: "bg-orange-50 border-orange-200",
  quiz: "bg-green-50 border-green-200",
  game: "bg-pink-50 border-pink-200",
  riddle: "bg-yellow-50 border-yellow-200",
  rhyme:  "bg-amber-50 border-amber-200",
};
